CREATE TABLE WorkItem
(
    [Id] BIGINT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
    [Number] NVARCHAR(MAX) NOT NULL,
    [StatusId] SMALLINT NOT NULL,
    [FlowId] SMALLINT NOT NULL,
    [MachineId] SMALLINT NULL,
    [PriorityId] SMALLINT NULL,
    [RetrieveCount] SMALLINT NOT NULL,
    [ValueGained] INTEGER NULL,
    [Processed] BIT NOT NULL,
    [IsValueGainedCalculated] BIT NOT NULL,
    [InsertedAtUTC] DATETIMEOFFSET(3) NOT NULL DEFAULT TODATETIMEOFFSET(GETUTCDATE(), 0),
    [UpdatedAtUTC] DATETIMEOFFSET(3) NOT NULL DEFAULT TODATETIMEOFFSET(GETUTCDATE(), 0)
)