CREATE TABLE LogMessages
(
    [Id] SMALLINT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
    [Level] NVARCHAR(10) NOT NULL,
    [Timestamp] DATETIMEOFFSET(3) NOT NULL DEFAULT TODATETIMEOFFSET(GETDATE(), 0),
    [Machine] NVARCHAR(50) NOT NULL,
    [Project] NVARCHAR(100) NOT NULL,
    [Flow] NVARCHAR(50) NOT NULL,
    [Subflow] NVARCHAR(50) NOT NULL,
    [Message] NVARCHAR(MAX) NOT NULL
)