CREATE TABLE Priority
(
    [Id] SMALLINT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
    [Name] NVARCHAR(255),
    [Value] SMALLINT NOT NULL,
    [InsertedAtUTC] DATETIMEOFFSET(3) NOT NULL DEFAULT TODATETIMEOFFSET(GETUTCDATE(), 0)
)