CREATE TABLE WorkItemData
(
    [Id] BIGINT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
    [WorkItemId] BIGINT NOT NULL,
    [DataContent] NVARCHAR(MAX) NOT NULL,
    [DataSource] NVARCHAR(MAX) NOT NULL,
    [InsertedAtUTC] DATETIMEOFFSET(3) NOT NULL DEFAULT TODATETIMEOFFSET(GETUTCDATE(), 0),
    [UpdatedAtUTC] DATETIMEOFFSET(3) NOT NULL DEFAULT TODATETIMEOFFSET(GETUTCDATE(), 0)
)